version: '2'
services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./nginx/nginx:/etc/nginx.conf.d
    depends_on:
      - web
  # docker-compose 에서 컨테이너(service) 단위를 묶음
  web:
    # 앱 service 이름
    build:
      dockerfile: Dockerfile # 빌드할 Docker 파일 위치

    command: gunicorn --bind 0.0.0.0:8000 BE.wsgi:application # docker-compose up 을 command 창에 입력하면 실행할 명령어
    volumes:
      # 로컬 폴더(.)와 docker 의 /code 폴더를 마운트(연결)
      - .:/code
    ports:
      # docker 와 로컬에서 서로 입력 출력할 포트, 접근할 포트
      - "8000:8000"
