# Generated by Django 4.2.4 on 2023-08-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_is_super"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_super",
            new_name="is_admin",
        ),
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
